# Generated by Django 5.1.2 on 2024-12-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setdrone", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstatus",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="setdrone.product"
            ),
        ),
    ]
