# Generated by Django 5.1.2 on 2024-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setdrone", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="house",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=100),
        ),
    ]
