# Generated by Django 5.1.2 on 2024-10-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setdrone", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
