# Generated by Django 5.1.2 on 2024-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setdrone", "0006_remove_profile_bio_remove_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("fruit", "Фрукты"), ("treat", "Лакомства")],
                default="fruit",
                max_length=20,
            ),
        ),
    ]
